# Generated by Django 5.1.2 on 2024-10-24 18:10

import Deals.models
import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(blank=True, help_text='Banner image for the tour page', null=True, upload_to='tours/banners/')),
                ('discount', models.IntegerField(blank=True, help_text='Example: 25', null=True)),
                ('discounted_destination_name', models.CharField(blank=True, help_text='Example: Srilanka', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_code', models.CharField(default=Deals.models.generate_package_code, max_length=50, unique=True)),
                ('location', models.CharField(max_length=255)),
                ('short_description', ckeditor.fields.RichTextField()),
                ('destination', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price per person', max_digits=10)),
                ('total_seats', models.IntegerField()),
                ('available_seats', models.IntegerField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Sold Out', 'Sold Out'), ('Cancelled', 'Cancelled')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(default='tours/default.jpg', upload_to='tours/')),
                ('bannerimage', models.ImageField(default='tour_banners/default.jpg', upload_to='tour_banners/')),
                ('cancellation_policy', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('additional_services', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('duration', models.CharField(max_length=50, null=True)),
                ('overview', ckeditor.fields.RichTextField(blank=True, help_text='Brief overview of the package', null=True)),
                ('banner_image', models.ImageField(blank=True, help_text='Banner image for the single tour', null=True, upload_to='tours_details/banners/')),
                ('included', ckeditor.fields.RichTextField(blank=True, help_text='What is included in this package', null=True)),
                ('excluded', ckeditor.fields.RichTextField(blank=True, help_text='What is excluded from this package', null=True)),
                ('flight_details', models.CharField(blank=True, help_text='Airplane name with flight code', max_length=100, null=True)),
                ('minimum_age', models.IntegerField(blank=True, help_text='Minimum age requirement for this package', null=True)),
                ('departure_location', models.CharField(default='Departure location_Name', max_length=200)),
                ('travel_direction', models.FileField(blank=True, help_text='Upload pdf file', null=True, upload_to='downloads/pdfs/')),
                ('documentations', models.FileField(blank=True, help_text='Upload pdf file', null=True, upload_to='downloads/pdfs/')),
                ('logo_assets', models.FileField(blank=True, help_text='Upload pdf file', null=True, upload_to='downloads/pdfs/')),
                ('hot_deal', models.BooleanField(default=False, help_text='Select if this package should appear on hot deal part')),
                ('show_on_homepage', models.BooleanField(default=False, help_text='Select if this package should appear on the homepage')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.customuser')),
            ],
            options={
                'permissions': [('can_crud_package', 'Can CRUD Package')],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Booked', 'Booked'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], max_length=20)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Refunded', 'Refunded')], max_length=20)),
                ('travel_status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed')], max_length=20)),
                ('price_at_booking', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('address_1', models.CharField(max_length=255, null=True)),
                ('address_2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('zip_code', models.CharField(max_length=20, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.customuser')),
                ('package_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Deals.package')),
            ],
        ),
    ]
