# Generated by Django 5.1.2 on 2024-10-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='image_url',
        ),
        migrations.AddField(
            model_name='package',
            name='image',
            field=models.ImageField(default='tours/default.jpg', upload_to='tours/'),
        ),
    ]
