# Generated by Django 5.1.2 on 2024-10-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deals', '0002_alter_booking_customer_id_alter_package_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='additional_services',
        ),
        migrations.RemoveField(
            model_name='package',
            name='banner_image',
        ),
        migrations.RemoveField(
            model_name='package',
            name='cancellation_policy',
        ),
        migrations.AlterField(
            model_name='package',
            name='bannerimage',
            field=models.ImageField(default='tour_banners/default.jpg', help_text='Banner image for the single tour', upload_to='tour_banners/'),
        ),
    ]
