# Generated by Django 5.1.2 on 2024-10-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deals', '0002_remove_package_image_url_package_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='package_name',
            new_name='location',
        ),
        migrations.AddField(
            model_name='package',
            name='duration',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price per person', max_digits=10),
        ),
    ]
