# Generated by Django 5.1.2 on 2024-10-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deals', '0004_tour_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour_page',
            name='bannerimage',
            field=models.ImageField(blank=True, null=True, upload_to='tour_banners/'),
        ),
    ]
