# Generated by Django 5.1.2 on 2024-10-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deals', '0005_package_child_price_alter_package_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={},
        ),
        migrations.AddField(
            model_name='package',
            name='offer',
            field=models.CharField(blank=True, help_text='Special offers for the package', max_length=255, null=True),
        ),
    ]
