# Generated by Django 5.1.2 on 2024-10-20 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deals', '0007_package_show_on_homepage_alter_tour_page_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Banner image for the package', null=True, upload_to='tours/banners/'),
        ),
        migrations.AddField(
            model_name='package',
            name='excluded',
            field=models.TextField(blank=True, help_text='What is excluded from this package', null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='flight_details',
            field=models.CharField(blank=True, help_text='Airplane name with flight code', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='included',
            field=models.TextField(blank=True, help_text='What is included in this package', null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='overview',
            field=models.TextField(blank=True, help_text='Brief overview of the package', null=True),
        ),
    ]
