# Generated by Django 5.1.2 on 2024-11-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deals', '0008_destination'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='address_1',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='address_2',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='city',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='image',
            field=models.ImageField(blank=True, default='destinations/images/default-image.jpg', help_text='Image of the destination', null=True, upload_to='destinations/images/'),
        ),
    ]
