# Generated by Django 5.1.2 on 2024-10-20 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Deals', '0008_package_banner_image_package_excluded_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='description',
            new_name='short_description',
        ),
    ]
