# Generated by Django 5.1.2 on 2024-11-15 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deals', '0009_rename_address_1_booking_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('bkash', 'Bkash'), ('nagad', 'Nagad'), ('rocket', 'Rocket')], max_length=20)),
                ('account_no', models.CharField(max_length=20)),
                ('transaction_id', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='Deals.booking')),
            ],
            options={
                'verbose_name': 'Payment Info',
                'verbose_name_plural': 'Payment Info',
            },
        ),
    ]
