# Generated by Django 5.1.2 on 2024-11-17 13:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Deals', '0010_paymentinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='tour_plan_description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Detailed description of the tour plan', null=True),
        ),
    ]
