# Generated by Django 5.1.2 on 2024-10-20 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deals', '0010_package_minimum_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
