# Generated by Django 5.1.2 on 2024-10-20 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deals', '0011_alter_package_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='departure_location',
            field=models.CharField(default='Departure location_Name', max_length=200),
        ),
    ]
