# Generated by Django 5.1.2 on 2024-11-18 19:23

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deals', '0011_package_tour_plan_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_description', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
