# Generated by Django 5.1.2 on 2024-11-21 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Deals', '0012_paymentdescription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentdescription',
            options={'verbose_name': 'Payment Description', 'verbose_name_plural': 'Payment Description'},
        ),
    ]
