# Generated by Django 5.1.2 on 2024-10-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deals', '0013_package_travel_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='documentations',
            field=models.FileField(blank=True, help_text='Upload pdf file', null=True, upload_to='downloads/pdfs/'),
        ),
        migrations.AddField(
            model_name='package',
            name='logo_assets',
            field=models.FileField(blank=True, help_text='Upload pdf file', null=True, upload_to='downloads/pdfs/'),
        ),
    ]
