# Generated by Django 5.1.2 on 2024-10-20 10:58

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deals', '0014_package_documentations_package_logo_assets'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='address_1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='address_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='message',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='zip_code',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
