# Generated by Django 5.1.2 on 2024-10-20 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deals', '0015_booking_address_1_booking_address_2_booking_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='booking',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
