# Generated by Django 5.1.2 on 2024-10-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deals', '0016_remove_booking_updated_at_alter_booking_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount_deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.IntegerField(blank=True, help_text='Example: 25', null=True)),
                ('discounted_destination_name', models.CharField(blank=True, help_text='Example: Srilanka', max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Tour_page',
        ),
        migrations.RemoveField(
            model_name='package',
            name='image',
        ),
        migrations.AddField(
            model_name='package',
            name='bannerimage',
            field=models.ImageField(blank=True, null=True, upload_to='tour_banners/'),
        ),
    ]
