# Generated by Django 4.2.4 on 2025-09-01 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Deals', '0017_booking_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='short_description',
        ),
    ]
