# Generated by Django 5.1.2 on 2024-10-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deals', '0017_discount_deal_delete_tour_page_remove_package_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
