# Generated by Django 5.1.2 on 2024-10-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deals', '0018_booking_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='image',
            field=models.ImageField(default='tours/default.jpg', upload_to='tours/'),
        ),
    ]
