# Generated by Django 5.1.2 on 2024-10-27 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermessage',
            options={'verbose_name_plural': 'Messages<span style="color:red, font-weight:bold">Shoily</span>'},
        ),
    ]
