# Generated by Django 4.2.4 on 2024-10-26 10:21

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Deals', '0002_alter_booking_customer_id_alter_package_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image1', models.ImageField(upload_to='about/')),
                ('image2', models.ImageField(upload_to='about/')),
                ('list_item_1', models.CharField(max_length=255)),
                ('list_item_2', models.CharField(max_length=255)),
                ('list_item_3', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Destinationinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(upload_to='destination_banner/')),
                ('description', models.TextField(default='No description available.')),
            ],
            options={
                'verbose_name': 'Destination',
                'verbose_name_plural': 'Destinationinfo',
            },
        ),
        migrations.CreateModel(
            name='FooterContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='footer_logos/')),
                ('site_name', models.CharField(max_length=255, null=True)),
                ('info_text', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('copyright_year', models.PositiveIntegerField(blank=True, null=True)),
                ('instagram', models.CharField(blank=True, max_length=255, null=True)),
                ('twitter', models.CharField(blank=True, max_length=255, null=True)),
                ('youtube', models.CharField(blank=True, max_length=255, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=255, null=True)),
                ('facebook', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FooterGalleryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Footer gallery group',
                'verbose_name_plural': 'Footer gallery groups',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(upload_to='gallery/')),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': 'Gallery images',
            },
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, default='default_images/default_logo.png', null=True, upload_to='header/logo/')),
                ('icon', models.ImageField(blank=True, default='default_images/default_icon.png', null=True, upload_to='header/icons/')),
                ('header_banner', models.ImageField(blank=True, default='default_images/default_banner.jpg', null=True, upload_to='header/banner/')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('gallery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Homepage.gallery')),
            ],
        ),
        migrations.CreateModel(
            name='FooterGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='footer_gallery/')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Homepage.footergallerygroup')),
            ],
            options={
                'verbose_name': 'Footer gallery',
                'verbose_name_plural': 'Footer galleries',
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor.fields.RichTextField(help_text='Description of the destination')),
                ('address', models.CharField(help_text='Address of the destination', max_length=255, null=True)),
                ('visa_requirements', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', help_text='Visa requirements', max_length=3)),
                ('country', models.CharField(help_text='Country name', max_length=255, null=True)),
                ('languages_spoken', models.CharField(help_text='Languages spoken at destination', max_length=255, null=True)),
                ('currency_used', models.CharField(help_text='Currency used in the country', max_length=100, null=True)),
                ('distance', models.DecimalField(decimal_places=1, help_text='Distance to the destination', max_digits=10, null=True)),
                ('support_phone', models.CharField(help_text='Support phone number', max_length=20, null=True)),
                ('emergency_email', models.EmailField(help_text='Emergency contact email', max_length=254, null=True)),
                ('banner_image', models.ImageField(blank=True, help_text='Banner image for the destination', null=True, upload_to='destination_banner/')),
                ('package', models.ForeignKey(default='destination name', on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='Deals.package')),
            ],
        ),
    ]
