# Generated by Django 5.1.2 on 2024-10-19 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinationimage',
            name='name',
            field=models.CharField(default='Unnamed Image', max_length=255),
        ),
    ]
