# Generated by Django 4.2.4 on 2024-10-26 10:27

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Deals', '0002_alter_booking_customer_id_alter_package_creator'),
        ('Homepage', '0002_delete_destination'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor.fields.RichTextField(help_text='Description of the destination')),
                ('address', models.CharField(help_text='Address of the destination', max_length=255, null=True)),
                ('visa_requirements', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', help_text='Visa requirements', max_length=3)),
                ('country', models.CharField(help_text='Country name', max_length=255, null=True)),
                ('languages_spoken', models.CharField(help_text='Languages spoken at destination', max_length=255, null=True)),
                ('currency_used', models.CharField(help_text='Currency used in the country', max_length=100, null=True)),
                ('distance', models.DecimalField(decimal_places=1, help_text='Distance to the destination', max_digits=10, null=True)),
                ('support_phone', models.CharField(help_text='Support phone number', max_length=20, null=True)),
                ('emergency_email', models.EmailField(help_text='Emergency contact email', max_length=254, null=True)),
                ('banner_image', models.ImageField(blank=True, help_text='Banner image for the destination', null=True, upload_to='destination_banner/')),
                ('package', models.ForeignKey(default='destination name', on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='Deals.package')),
            ],
        ),
    ]
