# Generated by Django 5.1.2 on 2024-10-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0004_remove_destination_banner_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='image',
            field=models.ImageField(blank=True, help_text='Image of the destination', null=True, upload_to='destinations/images/'),
        ),
        migrations.AddField(
            model_name='destination',
            name='show_on_homepage',
            field=models.BooleanField(default=False, help_text='Show this destination on the homepage'),
        ),
    ]
