# Generated by Django 5.1.2 on 2024-10-26 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0005_destination_image_destination_show_on_homepage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='package',
            new_name='location',
        ),
    ]
