# Generated by Django 5.1.2 on 2024-10-26 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0006_rename_package_destination_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='location',
            new_name='package',
        ),
    ]
