# Generated by Django 5.1.2 on 2024-11-16 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0009_delete_destination'),
    ]

    operations = [
        migrations.RenameField(
            model_name='header',
            old_name='icon',
            new_name='favicon',
        ),
    ]
