# Generated by Django 4.2.4 on 2025-09-01 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0011_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footercontent',
            name='copyright_year',
        ),
    ]
